const _countryCodes = [
	{
		imgUrl: "UA",
		phoneCode: "380",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "AE",
		phoneCode: "971",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "AF",
		phoneCode: "93",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "AL",
		phoneCode: "355",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "DZ",
		phoneCode: "213",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "AD",
		phoneCode: "376",
		phoneNumberLength: 6,
		phoneNumberLengthWithCode: 9,
	},
	{
		imgUrl: "AO",
		phoneCode: "244",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "AR",
		phoneCode: "54",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "AM",
		phoneCode: "374",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "AU",
		phoneCode: "61",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "AT",
		phoneCode: "43",
		phoneNumberLength: 4,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "AZ",
		phoneCode: "994",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 13,
	},
	{
		imgUrl: "BS",
		phoneCode: "1-242",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BH",
		phoneCode: "973",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BD",
		phoneCode: "880",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 13,
	},
	{
		imgUrl: "BB",
		phoneCode: "1-246",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BY",
		phoneCode: "375",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "BE",
		phoneCode: "32",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BZ",
		phoneCode: "501",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BJ",
		phoneCode: "229",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BT",
		phoneCode: "975",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BO",
		phoneCode: "591",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BA",
		phoneCode: "387",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BW",
		phoneCode: "267",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "BR",
		phoneCode: "55",
		phoneNumberLength: 11,
		phoneNumberLengthWithCode: 13,
	},
	{
		imgUrl: "BN",
		phoneCode: "673",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "BG",
		phoneCode: "359",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "BF",
		phoneCode: "226",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "BI",
		phoneCode: "257",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "KH",
		phoneCode: "855",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "CM",
		phoneCode: "237",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "CA",
		phoneCode: "1",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "CV",
		phoneCode: "238",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "CF",
		phoneCode: "236",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "TD",
		phoneCode: "235",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "CL",
		phoneCode: "56",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "CN",
		phoneCode: "86",
		phoneNumberLength: 11,
		phoneNumberLengthWithCode: 13,
	},
	{
		imgUrl: "CO",
		phoneCode: "57",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "KM",
		phoneCode: "269",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "CG",
		phoneCode: "242",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "CD",
		phoneCode: "243",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "CR",
		phoneCode: "506",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "HR",
		phoneCode: "385",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "CU",
		phoneCode: "53",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "CY",
		phoneCode: "357",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "CZ",
		phoneCode: "420",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "DK",
		phoneCode: "45",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "DJ",
		phoneCode: "253",
		phoneNumberLength: 6,
		phoneNumberLengthWithCode: 9,
	},
	{
		imgUrl: "DM",
		phoneCode: "1-767",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "DO",
		phoneCode: "1-809",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 13,
	},
	{
		imgUrl: "EC",
		phoneCode: "593",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "EG",
		phoneCode: "20",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "SV",
		phoneCode: "503",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "GQ",
		phoneCode: "240",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "ER",
		phoneCode: "291",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "EE",
		phoneCode: "372",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "SZ",
		phoneCode: "268",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "ET",
		phoneCode: "251",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "FJ",
		phoneCode: "679",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "FI",
		phoneCode: "358",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "FR",
		phoneCode: "33",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "GA",
		phoneCode: "241",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "GM",
		phoneCode: "220",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "GE",
		phoneCode: "995",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "DE",
		phoneCode: "49",
		phoneNumberLength: 11,
		phoneNumberLengthWithCode: 13,
	},
	{
		imgUrl: "GH",
		phoneCode: "233",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "GR",
		phoneCode: "30",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "GD",
		phoneCode: "1-473",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "GT",
		phoneCode: "502",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "GN",
		phoneCode: "224",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "GW",
		phoneCode: "245",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "GY",
		phoneCode: "592",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "HT",
		phoneCode: "509",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "HN",
		phoneCode: "504",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "HU",
		phoneCode: "36",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "IS",
		phoneCode: "354",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "IN",
		phoneCode: "91",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "ID",
		phoneCode: "62",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "IR",
		phoneCode: "98",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "IQ",
		phoneCode: "964",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 13,
	},
	{
		imgUrl: "IE",
		phoneCode: "353",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "IL",
		phoneCode: "972",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "IT",
		phoneCode: "39",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "JM",
		phoneCode: "1-876",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "JP",
		phoneCode: "81",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "JO",
		phoneCode: "962",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},

	{
		imgUrl: "KE",
		phoneCode: "254",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "KI",
		phoneCode: "686",
		phoneNumberLength: 5,
		phoneNumberLengthWithCode: 9,
	},
	{
		imgUrl: "KP",
		phoneCode: "850",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "KR",
		phoneCode: "82",
		phoneNumberLength: 11,
		phoneNumberLengthWithCode: 13,
	},
	{
		imgUrl: "KW",
		phoneCode: "965",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "KG",
		phoneCode: "996",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "LA",
		phoneCode: "856",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "LV",
		phoneCode: "371",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "LB",
		phoneCode: "961",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "LS",
		phoneCode: "266",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "LR",
		phoneCode: "231",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "LY",
		phoneCode: "218",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "LI",
		phoneCode: "423",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "LT",
		phoneCode: "370",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "LU",
		phoneCode: "352",
		phoneNumberLength: 6,
		phoneNumberLengthWithCode: 9,
	},
	{
		imgUrl: "MG",
		phoneCode: "261",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "MW",
		phoneCode: "265",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "MY",
		phoneCode: "60",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "MV",
		phoneCode: "960",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "ML",
		phoneCode: "223",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "MT",
		phoneCode: "356",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "MH",
		phoneCode: "692",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "MR",
		phoneCode: "222",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "MU",
		phoneCode: "230",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "MX",
		phoneCode: "52",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "FM",
		phoneCode: "691",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "MD",
		phoneCode: "373",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "MC",
		phoneCode: "377",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "MN",
		phoneCode: "976",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "ME",
		phoneCode: "382",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "MA",
		phoneCode: "212",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "MZ",
		phoneCode: "258",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "MM",
		phoneCode: "95",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "NA",
		phoneCode: "264",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "NR",
		phoneCode: "674",
		phoneNumberLength: 4,
		phoneNumberLengthWithCode: 8,
	},
	{
		imgUrl: "NP",
		phoneCode: "977",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "NL",
		phoneCode: "31",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "NZ",
		phoneCode: "64",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "NI",
		phoneCode: "505",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "NE",
		phoneCode: "227",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "NG",
		phoneCode: "234",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "MK",
		phoneCode: "389",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "NO",
		phoneCode: "47",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "OM",
		phoneCode: "968",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "PK",
		phoneCode: "92",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "PW",
		phoneCode: "680",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "PA",
		phoneCode: "507",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "PG",
		phoneCode: "675",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "PY",
		phoneCode: "595",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "PE",
		phoneCode: "51",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "PH",
		phoneCode: "63",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "PL",
		phoneCode: "48",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "PT",
		phoneCode: "351",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "QA",
		phoneCode: "974",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "RE",
		phoneCode: "262",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "RO",
		phoneCode: "40",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "RU",
		phoneCode: "7",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "RW",
		phoneCode: "250",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},

	{
		imgUrl: "SH",
		phoneCode: "290",
		phoneNumberLength: 6,
		phoneNumberLengthWithCode: 9,
	},
	{
		imgUrl: "KN",
		phoneCode: "1-869",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "LC",
		phoneCode: "1-758",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "MF",
		phoneCode: "590",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},

	{
		imgUrl: "VC",
		phoneCode: "1-784",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "WS",
		phoneCode: "685",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 8,
	},
	{
		imgUrl: "ST",
		phoneCode: "239",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "SN",
		phoneCode: "221",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "RS",
		phoneCode: "381",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "SC",
		phoneCode: "248",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "SL",
		phoneCode: "232",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 10,
	},
	{
		imgUrl: "SG",
		phoneCode: "65",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 10,
	},

	{
		imgUrl: "SY",
		phoneCode: "963",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "TJ",
		phoneCode: "992",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "TZ",
		phoneCode: "255",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "TG",
		phoneCode: "228",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "TO",
		phoneCode: "676",
		phoneNumberLength: 5,
		phoneNumberLengthWithCode: 9,
	},
	{
		imgUrl: "TT",
		phoneCode: "1-868",
		phoneNumberLength: 7,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "TN",
		phoneCode: "216",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "TR",
		phoneCode: "90",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "TM",
		phoneCode: "993",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "TV",
		phoneCode: "688",
		phoneNumberLength: 4,
		phoneNumberLengthWithCode: 8,
	},
	{
		imgUrl: "UG",
		phoneCode: "256",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "UA",
		phoneCode: "380",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "AE",
		phoneCode: "971",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "GB",
		phoneCode: "44",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "US",
		phoneCode: "1",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "UY",
		phoneCode: "598",
		phoneNumberLength: 8,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "UZ",
		phoneCode: "998",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "VU",
		phoneCode: "678",
		phoneNumberLength: 5,
		phoneNumberLengthWithCode: 9,
	},
	{
		imgUrl: "VE",
		phoneCode: "58",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "VN",
		phoneCode: "84",
		phoneNumberLength: 10,
		phoneNumberLengthWithCode: 11,
	},
	{
		imgUrl: "WF",
		phoneCode: "681",
		phoneNumberLength: 5,
		phoneNumberLengthWithCode: 9,
	},
	{
		imgUrl: "YE",
		phoneCode: "967",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "ZM",
		phoneCode: "260",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
	{
		imgUrl: "ZW",
		phoneCode: "263",
		phoneNumberLength: 9,
		phoneNumberLengthWithCode: 12,
	},
];

export const getCounrtyCodes = (info = null) => {
	if (info) {
		return _countryCodes.find((item) => info.startsWith(item.phoneCode));
	} else {
		return _countryCodes;
	}
};
